id = "macos-dark-enhanced"
name = "macOS Classic Dark Theme Enhanced"
description = "A macOS native style dark theme. A fork of macOS Classic Dark2 Theme by @huacnlee"
version = "1.0.0"
schema_version = 1
authors = ["sidharthpunathil"]
repository = "https://github.com/sidharthpunathil/zed-theme-macos-dark-enhanced"
